### ISSUE TITLE
redinessProbe in basic template produce a huge logs

### ISSUE THREAD

**Issue by lenosi** [jboss-container-images/amq-interconnect-1-openshift-image#22]
We (@fgiorgetti and me) found that "something".. in the logs produces the infinite loop of these:

```	
2018-10-18 13:10:58.228333 +0000 SERVER (info) [3165]: Accepted connection to 0.0.0.0:amqp from 10.128.0.1:46864		
2018-10-18 13:10:58.228586 +0000 SERVER (info) [3165]: Connection from 1.1.0.1:46864 (to 0.0.0.0:amqp) failed: amqp:connection:framing-error No valid protocol header found
```
These in the logs is annoying and breaks the access (for me) to the logs from OCP 3.10 Console.
And the problem is maybe there because of the basic template use for "readinessProbe" TCP connection and the sasldb already use the WebSocket connection. 

###  The sasldb template

https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/blob/3dd70f008c468524dbc03ef34d30e5da2a040e06/templates/amq-interconnect-1-sasldb-auth.yaml#L86-L93

https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/blob/3dd70f008c468524dbc03ef34d30e5da2a040e06/templates/amq-interconnect-1-sasldb-auth.yaml#L229-L236

### The basic template

https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/blob/3dd70f008c468524dbc03ef34d30e5da2a040e06/templates/amq-interconnect-1-basic.yaml#L38-L43

https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/blob/3dd70f008c468524dbc03ef34d30e5da2a040e06/templates/amq-interconnect-1-basic.yaml#L200-L205

**Comment by grs** [comment]
Fixed: https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/commit/33dd3bd800dedd478be9018b2a6f3e6c1e96431b
